### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Aslemammad** [alithecodeguy/persian-javascript.info#1]
منم قطعا میخوام کار کنم و کمک کنم چونکه خوشم اومد از همچین ایده ساده و خفنی. یه سری وظایف و راهی تعیین کنید که بتونم کانتریبیوت کنم.

**Comment by hmosavand** [comment]
منم دوست دارم جزو تیم باشم فقط دستوالعمل درست کنید که وظایف و بخش ها مشخص. باشه 
:))))

**Comment by alithecodeguy** [comment]
> منم قطعا میخوام کار کنم و کمک کنم چونکه خوشم اومد از همچین ایده ساده و خفنی. یه سری وظایف و راهی تعیین کنید که بتونم کانتریبیوت کنم.

بسیار هم عالی. 
از طریق آیدی زیر در تلگرام پیام بدین در ارتباط باشیم
@alithecodeguy

**Comment by alithecodeguy** [comment]
> منم قطعا میخوام کار کنم و کمک کنم چونکه خوشم اومد از همچین ایده ساده و خفنی. یه سری وظایف و راهی تعیین کنید که بتونم کانتریبیوت کنم.

بسیار هم عالی. از طریق آیدی زیر در تلگرام پیام بدین در ارتباط باشیم:
@alithecodeguy
