### ISSUE TITLE
اشتباه در ترجمه

### ISSUE THREAD

**Issue by mehdico** [alithecodeguy/persian-javascript.info#3]
سلام
من گذرا یک نگاهی داشتم مینداختم با جمله ای در فایل شماره ۹ برخورد کردم (اولین جمله) که نوشته بود

«یک متغیر در جاوا اسکریپت همیشه نوع مشخصی دارد»

این جمله صد در صد اشتباهه.
رفتم و توی سایت رفرنس اصلی رو بررسی کردم دیدم جمله اصلی اینه
A value in JavaScript is always of a certain type.

یعنی ولیو ترجمه شده به متغیر در حالی ولیو یعنی مقدار و تفاوت این دو در این جمله کاملا معنی جمله رو عوض میکنه و جمله رو اشتباه میکنه.

سپاس

**Comment by hmosavand** [comment]
بنظرم ترجمه ها بیاد و گروهی به عنوان هد بالا دست اونا رو تایید کنن اینطور بهتره یعنی یه گروه تصحیح بعد ترجمه هم داشته باشیم

**Comment by alithecodeguy** [comment]
> بنظرم ترجمه ها بیاد و گروهی به عنوان هد بالا دست اونا رو تایید کنن اینطور بهتره یعنی یه گروه تصحیح بعد ترجمه هم داشته باشیم 

موافقم. روش پیشنهادیت چیه؟ چطوری میتونم پیشنهادتو عملی کنیم؟

**Comment by alithecodeguy** [comment]
> سلام
> 
> من گذرا یک نگاهی داشتم مینداختم با جمله ای در فایل شماره ۹ برخورد کردم (اولین جمله) که نوشته بود
> 
> 
> 
> «یک متغیر در جاوا اسکریپت همیشه نوع مشخصی دارد»
> 
> 
> 
> این جمله صد در صد اشتباهه.
> 
> رفتم و توی سایت رفرنس اصلی رو بررسی کردم دیدم جمله اصلی اینه
> 
> A value in JavaScript is always of a certain type.
> 
> 
> 
> یعنی ولیو ترجمه شده به متغیر در حالی ولیو یعنی مقدار و تفاوت این دو در این جمله کاملا معنی جمله رو عوض میکنه و جمله رو اشتباه میکنه.
> 
> 
> 
> سپاس

سلام 
کاملا حق با شماست. ممنون. اصلاح میشه

**Comment by alithecodeguy** [comment]
issue fixed
