### ISSUE TITLE
الف اضافه 

### ISSUE THREAD

**Issue by Farbod29** [alithecodeguy/persian-javascript.info#4]
![Screenshot 2021-05-30 at 23 57 57](https://user-images.githubusercontent.com/17232450/120381371-a20d0a00-c322-11eb-85ce-6a95b167b5a4.png)
![Screenshot 2021-05-31 at 23 34 36](https://user-images.githubusercontent.com/17232450/120381417-ae916280-c322-11eb-8614-876472780636.png)
توی سویچ کیس
جزوه ۱۸

**Comment by alithecodeguy** [comment]
> ![Screenshot 2021-05-30 at 23 57 57](https://user-images.githubusercontent.com/17232450/120381371-a20d0a00-c322-11eb-85ce-6a95b167b5a4.png)
> ![Screenshot 2021-05-31 at 23 34 36](https://user-images.githubusercontent.com/17232450/120381417-ae916280-c322-11eb-8614-876472780636.png)
> توی سویچ کیس
> جزوه ۱۸

tnx
