### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by Farbod29** [alithecodeguy/persian-javascript.info#5]
better maybe, comment alert or ?? near function 

![Screenshot 2021-06-01 at 22 20 33](https://user-images.githubusercontent.com/17232450/120385350-97a13f00-c327-11eb-984a-49bb86410579.png)

**Comment by Farbod29** [comment]
![Screenshot 2021-06-01 at 23 30 14](https://user-images.githubusercontent.com/17232450/120392824-54e46480-c331-11eb-829e-280cfe0ab73b.png)
25-> احمق

**Comment by alithecodeguy** [comment]
Tnx Frabod But I didn't get the problem

**Comment by alithecodeguy** [comment]
> better maybe, comment alert or ?? near function
> 
> ![Screenshot 2021-06-01 at 22 20 33](https://user-images.githubusercontent.com/17232450/120385350-97a13f00-c327-11eb-984a-49bb86410579.png)

Tnx Frabod But I didn't get the problem

**Comment by alithecodeguy** [comment]
> ![Screenshot 2021-06-01 at 23 30 14](https://user-images.githubusercontent.com/17232450/120392824-54e46480-c331-11eb-829e-280cfe0ab73b.png)
> 25-> احمق

Tnx

**Comment by alithecodeguy** [comment]
done.
